#!/bin/bash
# AFEWMORE script

PROGNAME=$(basename $0)
VERSION='0.0.5'

function usage
{
  #####
  # Function to display usage message (does not exit)
  # No arguments
  #####

  echo "Usage: ${PROGNAME} [-hv] [-d dir] [-n num] instance"
}

function helptext
{
  #####
  #   Function to display help message for program
  #   No arguments
  #####
  
  local tab=$(echo -en "\t\t")
  cat <<- -EOF-

  ${PROGNAME} ver. ${VERSION}

  The afewmore tool can be used to duplicate a given EC2 instance.  When
     doing so, it creates multiple new instances and populates their data
     directory by copying the data from the original.
  
  $(usage)
  
  OPTIONS
     The source instance is specified via the mandatory argument to afewmore.
     In addition, the following command-line options are supported:

     -d dir   Copy the contents of this data directory from the orignal source
        instance to all the new instances.  If not specified, defaults
        to /data.

     -h       Print a usage statement and exit.

     -n num   Create this many new instances.  If not specified, defaults to
        10.

     -v       Be verbose.

  -EOF-
}


###########################################################################
#   Program starts here
###########################################################################

# Process command line arguments

num=2
dir=/data

if [ "$1" = "--help" ]; then
    helptext
    exit
fi

# Display usage message if no options or arguments are given

if [ "$1" = "" ]; then
  usage
  exit 1
fi

# Process possible option/argument combinations
verbose=0
while [ $# -ne 1 ]; do
    case $1 in
        -d )    shift
#                if [ ! -d $1 ]; then
#                    echo "$1 is not a directory!"
#                    exit 1
#                fi
                dir=$1
                ;;
        -n )    shift
                num=$1
                ;;
        -h )    usage
                exit
                ;;
        -v )    verbose=1
                ;;
        * )     usage
                exit 1
    esac
    # echo $#
    shift
done

instance=$1

# echo "The arguments are as follows."
# echo $dir
# echo $num
# echo $instance

InstanceType=$(aws ec2 describe-instances --instance-ids $instance --output text --query 'Reservations[0].Instances[0].InstanceType')
#echo "InstanceType "$InstanceType

PublicDnsName=$(aws ec2 describe-instances --instance-ids $instance --output text --query 'Reservations[0].Instances[0].PublicDnsName')
#echo "PublicDnsName "$PublicDnsName

ImageId=$(aws ec2 describe-instances --instance-ids $instance --output text --query 'Reservations[0].Instances[0].ImageId')
#echo "ImageId "$ImageId

GroupId=$(aws ec2 describe-instances --instance-ids $instance --output text --query 'Reservations[0].Instances[0].SecurityGroups[*].GroupId')
#echo "GroupId "$GroupId

KeyName=$(aws ec2 describe-instances --instance-ids $instance --output text --query 'Reservations[0].Instances[0].KeyName')
#echo "KeyName "$KeyName
if [ "$verbose" = "1" ]; then
    echo "Target instance info received."
fi

aws ec2 run-instances --image-id $ImageId --key-name $KeyName --security-group-ids $GroupId --instance-type $InstanceType --count $num --output text --query 'Instances[*].InstanceId'>tempInstances.txt
if [ "$verbose" = "1" ]; then
    echo "Instances created."
fi

if [ "$verbose" = "1" ]; then
    scp -o StrictHostKeyChecking=no -i ~/devenv-key.pem -r ec2-user@$PublicDnsName:$dir tempData/
else
    scp -q -o StrictHostKeyChecking=no -i ~/devenv-key.pem -r ec2-user@$PublicDnsName:$dir tempData/
fi

if [ "$verbose" = "1" ]; then
    echo "Data copied from target instance."
    echo "Trying to connect to the new instances..this will take less than one minute.."
fi

sleep 55
instances=$(cat tempInstances.txt)
aws ec2 describe-instances --instance-ids $instances --output text --query 'Reservations[*].Instances[*].[InstanceId,PublicDnsName]' > tempInstances2.txt
if [ "$verbose" = "1" ]; then
    cat tempInstances2.txt | awk '{system("scp -o StrictHostKeyChecking=no -i ~/devenv-key.pem -r tempData/ ec2-user@"$2":$dir")}'
else
    cat tempInstances2.txt | awk '{system("scp -q -o StrictHostKeyChecking=no -i ~/devenv-key.pem -r tempData/ ec2-user@"$2":$dir")}'
fi

# cleaning temp files
rm -r tempData
#rm tempInstances.txt
#rm tempInstances2.txt
echo $instances | tr " " "\n"

if [ "$verbose" = "1" ]; then
    echo "Temp data cleared."
    echo "Program finished."
fi
# echo $?
